### ISSUE TITLE
Compression results in upside down document

### ISSUE THREAD

**Issue by florisre** [ElectricRCAircraftGuy/PDF2SearchablePDF#32]
After running a document through this great script with the compression option, the standard result is a perfect PDF file, the compressed versions though are all upside down.

**Comment by ElectricRCAircraftGuy** [comment]
@florisre , I'm not sure how I'd detect that. Let's have the fix for now be manual--ie: you have to do it manually. Please see my instructions here to rotate the PDF 180 deg via `qpdf --rotate=+180 in.pdf out.pdf` to fix it: [Unix & Linux: Command line: How do you rotate a PDF file 90 degrees?](https://unix.stackexchange.com/a/634882/114401). 

Are your upside-down versions still searchable? After fixing them with `qpdf` are they still compressed _and_ searchable?

**Comment by florisre** [comment]
The answer to all these questions is: yes. Thanks!
